---
title: "Guide_to_sigma"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Guide_to_sigma}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(SIGMA)
library(splatter)
library(ggplot2)

#Load sample data simulated with splatter
data("splatO")

expr <- counts(splatO)
expr <- expr[rowSums(expr)>0,]

#Normalize and log-transform the data
expr.norm <- t(t(expr)/colSums(expr))*10000
expr.norm.log <- log(expr.norm + 1)

#Create toy example of a data set
test.cluster <- as.character(splatO$Group)
test.cluster[test.cluster == "Group3"] <- "Group2"
test.cluster[test.cluster == "Group4"] <- "Group2"
```

```{r}
#Main funcion that calculates the clusterability
out <- sigma_funct(expr = expr.norm.log, clusters = test.cluster, exclude = data.frame(clsm = log(colSums(expr) + 1)))
```

```{r}
#Evaluate the output of the measure

#plot all values for sigma
plot_sigma(out)

#Plot all values for sigma and g_sigma
plot_all_sigmas(out)
plot_all_g_sigmas(out)

#obtain the values for sigma and additional information
get_info(out, "Group2")

#See which genes cause variances in the data
get_var_genes(out, "Group2")

#Check if the MP distribution fits to the data
plot_MP(out, "Group2")

#Check-out the singular vectors to evaluate the variances that are significant 

#Plot clusters
plot_singular_vectors(out, "Group2", colour = splatO$Group[test.cluster == "Group2"])

#Plot variance driving genes
plot_singular_vectors(out, "Group2", colour = "Gene401")

```
